version: '3'

services:
  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./env/.env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

  client:
    build:
      context: .
      dockerfile: ./docker/client/Dockerfile
    restart: always
    volumes:
      - ./client:/var/works/client
    ports:
      - 4200:4200

volumes:
  postgres: